language: node_js
node_js:
    - "node"

  before_install:
- openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv -in travis_rsa.enc -out travis_rsa -d
- chmod 600 travis_rsa
- mv travis_rsa ~/.ssh/id_rsa
- echo $DEPLOY_HOST_PUBLIC_KEY >> ~/.ssh/known_hosts

script:
- npm run lint
- npm test

deploy:
  provider: script
  script: bash scripts/deploy-to-prod.sh
  on:
    branch: main
